#empty
name : CI Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
# install java dependencies 
      run: mvn install
    - name: Run tests
      run: mvn test
    - name: Build project
      run: mvn package

